# Generated by Django 3.2.11 on 2024-01-26 15:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0004_signup_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Southindian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='images/')),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='products',
            new_name='Chinese',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='chinese',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='southindian',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myshop.southindian'),
            preserve_default=False,
        ),
    ]
