# Generated by Django 3.2.11 on 2024-01-28 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0006_alter_cartitem_southindian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='chinese',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myshop.chinese'),
        ),
    ]
