# Generated by Django 3.2.11 on 2024-02-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0007_alter_cartitem_chinese'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_No', models.CharField(max_length=10)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('People', models.IntegerField()),
                ('Message', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='signup_model',
            name='Email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='signup_model',
            name='Phone_No',
            field=models.CharField(max_length=10),
        ),
    ]
